// Copyright 2022 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: pkg/apis/ingress/ingress.proto

package ingress

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the node name.
type BackendName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name of the backend that posted the message
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// namespace of the backend that posted the message
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *BackendName) Reset() {
	*x = BackendName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackendName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendName) ProtoMessage() {}

func (x *BackendName) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendName.ProtoReflect.Descriptor instead.
func (*BackendName) Descriptor() ([]byte, []int) {
	return file_pkg_apis_ingress_ingress_proto_rawDescGZIP(), []int{0}
}

func (x *BackendName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackendName) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type EventMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Backend   *BackendName `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty"`
	Eventtype string       `protobuf:"bytes,2,opt,name=eventtype,proto3" json:"eventtype,omitempty"`
	Reason    string       `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message   string       `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *EventMessage) Reset() {
	*x = EventMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMessage) ProtoMessage() {}

func (x *EventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMessage.ProtoReflect.Descriptor instead.
func (*EventMessage) Descriptor() ([]byte, []int) {
	return file_pkg_apis_ingress_ingress_proto_rawDescGZIP(), []int{1}
}

func (x *EventMessage) GetBackend() *BackendName {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *EventMessage) GetEventtype() string {
	if x != nil {
		return x.Eventtype
	}
	return ""
}

func (x *EventMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EventMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EventReturn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *EventReturn) Reset() {
	*x = EventReturn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReturn) ProtoMessage() {}

func (x *EventReturn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReturn.ProtoReflect.Descriptor instead.
func (*EventReturn) Descriptor() ([]byte, []int) {
	return file_pkg_apis_ingress_ingress_proto_rawDescGZIP(), []int{2}
}

func (x *EventReturn) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// The response message containing the greetings
type Configurations struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Op:
	//	*Configurations_FullconfigOp
	//	*Configurations_DynamicconfigOp
	//	*Configurations_BackendconfigOp
	//	*Configurations_StreamconfigOp
	Op isConfigurations_Op `protobuf_oneof:"op"`
}

func (x *Configurations) Reset() {
	*x = Configurations{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Configurations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configurations) ProtoMessage() {}

func (x *Configurations) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configurations.ProtoReflect.Descriptor instead.
func (*Configurations) Descriptor() ([]byte, []int) {
	return file_pkg_apis_ingress_ingress_proto_rawDescGZIP(), []int{3}
}

func (m *Configurations) GetOp() isConfigurations_Op {
	if m != nil {
		return m.Op
	}
	return nil
}

func (x *Configurations) GetFullconfigOp() *Configurations_FullConfiguration {
	if x, ok := x.GetOp().(*Configurations_FullconfigOp); ok {
		return x.FullconfigOp
	}
	return nil
}

func (x *Configurations) GetDynamicconfigOp() *Configurations_DynamicConfiguration {
	if x, ok := x.GetOp().(*Configurations_DynamicconfigOp); ok {
		return x.DynamicconfigOp
	}
	return nil
}

func (x *Configurations) GetBackendconfigOp() *Configurations_BackendConfiguration {
	if x, ok := x.GetOp().(*Configurations_BackendconfigOp); ok {
		return x.BackendconfigOp
	}
	return nil
}

func (x *Configurations) GetStreamconfigOp() *Configurations_StreamConfiguration {
	if x, ok := x.GetOp().(*Configurations_StreamconfigOp); ok {
		return x.StreamconfigOp
	}
	return nil
}

type isConfigurations_Op interface {
	isConfigurations_Op()
}

type Configurations_FullconfigOp struct {
	FullconfigOp *Configurations_FullConfiguration `protobuf:"bytes,2,opt,name=fullconfig_op,json=fullconfigOp,proto3,oneof"`
}

type Configurations_DynamicconfigOp struct {
	DynamicconfigOp *Configurations_DynamicConfiguration `protobuf:"bytes,3,opt,name=dynamicconfig_op,json=dynamicconfigOp,proto3,oneof"`
}

type Configurations_BackendconfigOp struct {
	BackendconfigOp *Configurations_BackendConfiguration `protobuf:"bytes,4,opt,name=backendconfig_op,json=backendconfigOp,proto3,oneof"`
}

type Configurations_StreamconfigOp struct {
	StreamconfigOp *Configurations_StreamConfiguration `protobuf:"bytes,5,opt,name=streamconfig_op,json=streamconfigOp,proto3,oneof"`
}

func (*Configurations_FullconfigOp) isConfigurations_Op() {}

func (*Configurations_DynamicconfigOp) isConfigurations_Op() {}

func (*Configurations_BackendconfigOp) isConfigurations_Op() {}

func (*Configurations_StreamconfigOp) isConfigurations_Op() {}

// FullConfiguration messages are used for actions that triggers full resync
type Configurations_FullConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configuration []byte `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
}

func (x *Configurations_FullConfiguration) Reset() {
	*x = Configurations_FullConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Configurations_FullConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configurations_FullConfiguration) ProtoMessage() {}

func (x *Configurations_FullConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configurations_FullConfiguration.ProtoReflect.Descriptor instead.
func (*Configurations_FullConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_apis_ingress_ingress_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Configurations_FullConfiguration) GetConfiguration() []byte {
	if x != nil {
		return x.Configuration
	}
	return nil
}

// DynamicConfiguration actions are used only for endpoints/certificates changes
type Configurations_DynamicConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configuration []byte `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
}

func (x *Configurations_DynamicConfiguration) Reset() {
	*x = Configurations_DynamicConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Configurations_DynamicConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configurations_DynamicConfiguration) ProtoMessage() {}

func (x *Configurations_DynamicConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configurations_DynamicConfiguration.ProtoReflect.Descriptor instead.
func (*Configurations_DynamicConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_apis_ingress_ingress_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Configurations_DynamicConfiguration) GetConfiguration() []byte {
	if x != nil {
		return x.Configuration
	}
	return nil
}

// BackendConfiguration is used when the Ingress ConfigMap is changed
type Configurations_BackendConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configuration []byte `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
}

func (x *Configurations_BackendConfiguration) Reset() {
	*x = Configurations_BackendConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Configurations_BackendConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configurations_BackendConfiguration) ProtoMessage() {}

func (x *Configurations_BackendConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configurations_BackendConfiguration.ProtoReflect.Descriptor instead.
func (*Configurations_BackendConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_apis_ingress_ingress_proto_rawDescGZIP(), []int{3, 2}
}

func (x *Configurations_BackendConfiguration) GetConfiguration() []byte {
	if x != nil {
		return x.Configuration
	}
	return nil
}

// StreamConfiguration are the TCP and UDP streams (non L7)
type Configurations_StreamConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configuration []byte `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
}

func (x *Configurations_StreamConfiguration) Reset() {
	*x = Configurations_StreamConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Configurations_StreamConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configurations_StreamConfiguration) ProtoMessage() {}

func (x *Configurations_StreamConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configurations_StreamConfiguration.ProtoReflect.Descriptor instead.
func (*Configurations_StreamConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_apis_ingress_ingress_proto_rawDescGZIP(), []int{3, 3}
}

func (x *Configurations_StreamConfiguration) GetConfiguration() []byte {
	if x != nil {
		return x.Configuration
	}
	return nil
}

var File_pkg_apis_ingress_ingress_proto protoreflect.FileDescriptor

var file_pkg_apis_ingress_ingress_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x69, 0x6e, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x2f, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x09, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x76, 0x31, 0x22, 0x3f, 0x0a, 0x0b, 0x42,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x90, 0x01, 0x0a,
	0x0c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x30, 0x0a,
	0x07, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x65,
	0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x07, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x1d, 0x0a, 0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0xf2,
	0x04, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x52, 0x0a, 0x0d, 0x66, 0x75, 0x6c, 0x6c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f,
	0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x69, 0x6e, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x46, 0x75, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0c, 0x66, 0x75, 0x6c, 0x6c, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x4f, 0x70, 0x12, 0x5b, 0x0a, 0x10, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2e, 0x2e, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x44, 0x79, 0x6e, 0x61, 0x6d,
	0x69, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x00, 0x52, 0x0f, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x4f, 0x70, 0x12, 0x5b, 0x0a, 0x10, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x5f, 0x6f, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x69,
	0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0f,
	0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4f, 0x70, 0x12,
	0x58, 0x0a, 0x0f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f,
	0x6f, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x69, 0x6e, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0e, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4f, 0x70, 0x1a, 0x39, 0x0a, 0x11, 0x46, 0x75, 0x6c,
	0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24,
	0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x3c, 0x0a, 0x14, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x1a, 0x3c, 0x0a, 0x14, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x1a, 0x3b, 0x0a, 0x13, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x04, 0x0a,
	0x02, 0x6f, 0x70, 0x32, 0xa7, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4c, 0x0a, 0x13, 0x57, 0x61, 0x74, 0x63, 0x68, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x2e, 0x69,
	0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x19, 0x2e, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x76, 0x31,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x00, 0x30, 0x01, 0x12, 0x48, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x2e, 0x69, 0x6e, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65,
	0x1a, 0x19, 0x2e, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x00, 0x32, 0x53, 0x0a,
	0x0c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a,
	0x0c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x2e,
	0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x16, 0x2e, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x76, 0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x22, 0x00,
	0x28, 0x01, 0x42, 0x27, 0x5a, 0x25, 0x6b, 0x38, 0x73, 0x2e, 0x69, 0x6f, 0x2f, 0x69, 0x6e, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x2d, 0x6e, 0x67, 0x69, 0x6e, 0x78, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61,
	0x70, 0x69, 0x73, 0x2f, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pkg_apis_ingress_ingress_proto_rawDescOnce sync.Once
	file_pkg_apis_ingress_ingress_proto_rawDescData = file_pkg_apis_ingress_ingress_proto_rawDesc
)

func file_pkg_apis_ingress_ingress_proto_rawDescGZIP() []byte {
	file_pkg_apis_ingress_ingress_proto_rawDescOnce.Do(func() {
		file_pkg_apis_ingress_ingress_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_apis_ingress_ingress_proto_rawDescData)
	})
	return file_pkg_apis_ingress_ingress_proto_rawDescData
}

var file_pkg_apis_ingress_ingress_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_apis_ingress_ingress_proto_goTypes = []interface{}{
	(*BackendName)(nil),                         // 0: ingressv1.BackendName
	(*EventMessage)(nil),                        // 1: ingressv1.EventMessage
	(*EventReturn)(nil),                         // 2: ingressv1.EventReturn
	(*Configurations)(nil),                      // 3: ingressv1.Configurations
	(*Configurations_FullConfiguration)(nil),    // 4: ingressv1.Configurations.FullConfiguration
	(*Configurations_DynamicConfiguration)(nil), // 5: ingressv1.Configurations.DynamicConfiguration
	(*Configurations_BackendConfiguration)(nil), // 6: ingressv1.Configurations.BackendConfiguration
	(*Configurations_StreamConfiguration)(nil),  // 7: ingressv1.Configurations.StreamConfiguration
}
var file_pkg_apis_ingress_ingress_proto_depIdxs = []int32{
	0, // 0: ingressv1.EventMessage.backend:type_name -> ingressv1.BackendName
	4, // 1: ingressv1.Configurations.fullconfig_op:type_name -> ingressv1.Configurations.FullConfiguration
	5, // 2: ingressv1.Configurations.dynamicconfig_op:type_name -> ingressv1.Configurations.DynamicConfiguration
	6, // 3: ingressv1.Configurations.backendconfig_op:type_name -> ingressv1.Configurations.BackendConfiguration
	7, // 4: ingressv1.Configurations.streamconfig_op:type_name -> ingressv1.Configurations.StreamConfiguration
	0, // 5: ingressv1.Configuration.WatchConfigurations:input_type -> ingressv1.BackendName
	0, // 6: ingressv1.Configuration.GetConfigurations:input_type -> ingressv1.BackendName
	1, // 7: ingressv1.EventService.PublishEvent:input_type -> ingressv1.EventMessage
	3, // 8: ingressv1.Configuration.WatchConfigurations:output_type -> ingressv1.Configurations
	3, // 9: ingressv1.Configuration.GetConfigurations:output_type -> ingressv1.Configurations
	2, // 10: ingressv1.EventService.PublishEvent:output_type -> ingressv1.EventReturn
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_apis_ingress_ingress_proto_init() }
func file_pkg_apis_ingress_ingress_proto_init() {
	if File_pkg_apis_ingress_ingress_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_apis_ingress_ingress_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackendName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_ingress_ingress_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_ingress_ingress_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventReturn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_ingress_ingress_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Configurations); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_ingress_ingress_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Configurations_FullConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_ingress_ingress_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Configurations_DynamicConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_ingress_ingress_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Configurations_BackendConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_ingress_ingress_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Configurations_StreamConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_apis_ingress_ingress_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*Configurations_FullconfigOp)(nil),
		(*Configurations_DynamicconfigOp)(nil),
		(*Configurations_BackendconfigOp)(nil),
		(*Configurations_StreamconfigOp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_apis_ingress_ingress_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_apis_ingress_ingress_proto_goTypes,
		DependencyIndexes: file_pkg_apis_ingress_ingress_proto_depIdxs,
		MessageInfos:      file_pkg_apis_ingress_ingress_proto_msgTypes,
	}.Build()
	File_pkg_apis_ingress_ingress_proto = out.File
	file_pkg_apis_ingress_ingress_proto_rawDesc = nil
	file_pkg_apis_ingress_ingress_proto_goTypes = nil
	file_pkg_apis_ingress_ingress_proto_depIdxs = nil
}
